### ISSUE TITLE
Add icon component as prefix/suffix

### ISSUE THREAD

**Issue by odai-alali** [spatie/vue-tabs-component#35] opened 2017-11-16 08:45 UTC
Hi, Thanks for sharing this useful component.

There is this use case that I have a question about. We mostly use components to generate icons, like [here](https://github.com/Justineo/vue-awesome#usage).

How can I pass this icon/component to prefix?

**Comment by pieterjandesmedt** [comment] 2017-11-17 16:26
This works:
```html
<tab name="map" prefix="<i class='material-icons'>map</i>">
<tab name="beer" prefix="<i class='fa fa-beer'></i>">
```
It would probably work better with a `<slot>` than with the current html property, but that needs a PR.

**Comment by odai-alali** [comment] 2017-11-19 13:23
There is an old [branch](https://github.com/spatie/vue-tabs-component/tree/slots-for-prefix-and-suffix) that implements this 

I've just noticed it, I will try it later.

@sebastiandedeyne are there any plans to merge this with master?

**Comment by sebastiandedeyne** [comment] 2017-11-19 16:32
The implementation was never finished, because we never were able to find a complete working solution (other people have tried too in vain...)

Feel free to give it a go of course!

For now, you'll need to use @pieterjandesmedt's solution.

Duplicate of #8

**Closed as completed by sebastiandedeyne** 2017-11-19 16:32 UTC

**Comment by techenby** [comment] 2018-08-09 14:57
Instead of doing a slot for a prefix/sufix what about a slot for the whole name?
